[tool.poetry]
name = "chai"
version = "0.1.0"
description = "Client for Human-Apalache Interaction"
authors = ["Your Name <you@example.com>"]
license = "Apache2.0"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
