# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from chai import cmdExecutor_pb2 as chai_dot_cmdExecutor__pb2


class CmdExecutorStub(object):
    """A stateless serivce exposing Apalache's CLI via RPC calls
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.run = channel.unary_unary(
                '/shai.CmdExecutor/run',
                request_serializer=chai_dot_cmdExecutor__pb2.CmdRequest.SerializeToString,
                response_deserializer=chai_dot_cmdExecutor__pb2.CmdResponse.FromString,
                )


class CmdExecutorServicer(object):
    """A stateless serivce exposing Apalache's CLI via RPC calls
    """

    def run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CmdExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'run': grpc.unary_unary_rpc_method_handler(
                    servicer.run,
                    request_deserializer=chai_dot_cmdExecutor__pb2.CmdRequest.FromString,
                    response_serializer=chai_dot_cmdExecutor__pb2.CmdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shai.CmdExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CmdExecutor(object):
    """A stateless serivce exposing Apalache's CLI via RPC calls
    """

    @staticmethod
    def run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shai.CmdExecutor/run',
            chai_dot_cmdExecutor__pb2.CmdRequest.SerializeToString,
            chai_dot_cmdExecutor__pb2.CmdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
