"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import chai.cmdExecutor_pb2
import grpc

class CmdExecutorStub:
    """A stateless serivce exposing Apalache's CLI via RPC calls"""
    def __init__(self, channel: grpc.Channel) -> None: ...
    run: grpc.UnaryUnaryMultiCallable[
        chai.cmdExecutor_pb2.CmdRequest,
        chai.cmdExecutor_pb2.CmdResponse]


class CmdExecutorServicer(metaclass=abc.ABCMeta):
    """A stateless serivce exposing Apalache's CLI via RPC calls"""
    @abc.abstractmethod
    def run(self,
        request: chai.cmdExecutor_pb2.CmdRequest,
        context: grpc.ServicerContext,
    ) -> chai.cmdExecutor_pb2.CmdResponse: ...


def add_CmdExecutorServicer_to_server(servicer: CmdExecutorServicer, server: grpc.Server) -> None: ...
