"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ConnectRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___ConnectRequest = ConnectRequest

class Connection(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    id: typing.Text
    """The UUID identifying the client's connection"""

    def __init__(self,
        *,
        id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id"]) -> None: ...
global___Connection = Connection

class LoadModelRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CONN_FIELD_NUMBER: builtins.int
    SPEC_FIELD_NUMBER: builtins.int
    AUX_FIELD_NUMBER: builtins.int
    @property
    def conn(self) -> global___Connection:
        """The client's connextion"""
        pass
    spec: typing.Text
    """The root module of the spec"""

    @property
    def aux(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
        """Any auxiliary resources needed (e.g., extended modules)"""
        pass
    def __init__(self,
        *,
        conn: typing.Optional[global___Connection] = ...,
        spec: typing.Text = ...,
        aux: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["conn",b"conn"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["aux",b"aux","conn",b"conn","spec",b"spec"]) -> None: ...
global___LoadModelRequest = LoadModelRequest

class LoadModelResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SPEC_FIELD_NUMBER: builtins.int
    ERR_FIELD_NUMBER: builtins.int
    spec: typing.Text
    """A JSON encoded string with the Apalache IR representation of the loaded spec"""

    err: typing.Text
    """A string describing the error, if parsing fails"""

    def __init__(self,
        *,
        spec: typing.Text = ...,
        err: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["err",b"err","result",b"result","spec",b"spec"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["err",b"err","result",b"result","spec",b"spec"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["result",b"result"]) -> typing.Optional[typing_extensions.Literal["spec","err"]]: ...
global___LoadModelResponse = LoadModelResponse
