# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transExplorer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13transExplorer.proto\x12\x04shai\"\x10\n\x0e\x43onnectRequest\"\x18\n\nConnection\x12\n\n\x02id\x18\x01 \x01(\t\"M\n\x10LoadModelRequest\x12\x1e\n\x04\x63onn\x18\x01 \x01(\x0b\x32\x10.shai.Connection\x12\x0c\n\x04spec\x18\x02 \x01(\t\x12\x0b\n\x03\x61ux\x18\x03 \x03(\t\"<\n\x11LoadModelResponse\x12\x0e\n\x04spec\x18\x01 \x01(\tH\x00\x12\r\n\x03\x65rr\x18\x02 \x01(\tH\x00\x42\x08\n\x06result2\x87\x01\n\rTransExplorer\x12\x38\n\x0eOpenConnection\x12\x14.shai.ConnectRequest\x1a\x10.shai.Connection\x12<\n\tLoadModel\x12\x16.shai.LoadModelRequest\x1a\x17.shai.LoadModelResponseB9\n\x1b\x61t.forsyte.apalache.shai.v1B\x12TransExplorerProtoP\x01\xa2\x02\x03TEPb\x06proto3')



_CONNECTREQUEST = DESCRIPTOR.message_types_by_name['ConnectRequest']
_CONNECTION = DESCRIPTOR.message_types_by_name['Connection']
_LOADMODELREQUEST = DESCRIPTOR.message_types_by_name['LoadModelRequest']
_LOADMODELRESPONSE = DESCRIPTOR.message_types_by_name['LoadModelResponse']
ConnectRequest = _reflection.GeneratedProtocolMessageType('ConnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTREQUEST,
  '__module__' : 'transExplorer_pb2'
  # @@protoc_insertion_point(class_scope:shai.ConnectRequest)
  })
_sym_db.RegisterMessage(ConnectRequest)

Connection = _reflection.GeneratedProtocolMessageType('Connection', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTION,
  '__module__' : 'transExplorer_pb2'
  # @@protoc_insertion_point(class_scope:shai.Connection)
  })
_sym_db.RegisterMessage(Connection)

LoadModelRequest = _reflection.GeneratedProtocolMessageType('LoadModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOADMODELREQUEST,
  '__module__' : 'transExplorer_pb2'
  # @@protoc_insertion_point(class_scope:shai.LoadModelRequest)
  })
_sym_db.RegisterMessage(LoadModelRequest)

LoadModelResponse = _reflection.GeneratedProtocolMessageType('LoadModelResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOADMODELRESPONSE,
  '__module__' : 'transExplorer_pb2'
  # @@protoc_insertion_point(class_scope:shai.LoadModelResponse)
  })
_sym_db.RegisterMessage(LoadModelResponse)

_TRANSEXPLORER = DESCRIPTOR.services_by_name['TransExplorer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033at.forsyte.apalache.shai.v1B\022TransExplorerProtoP\001\242\002\003TEP'
  _CONNECTREQUEST._serialized_start=29
  _CONNECTREQUEST._serialized_end=45
  _CONNECTION._serialized_start=47
  _CONNECTION._serialized_end=71
  _LOADMODELREQUEST._serialized_start=73
  _LOADMODELREQUEST._serialized_end=150
  _LOADMODELRESPONSE._serialized_start=152
  _LOADMODELRESPONSE._serialized_end=212
  _TRANSEXPLORER._serialized_start=215
  _TRANSEXPLORER._serialized_end=350
# @@protoc_insertion_point(module_scope)
