"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc
import transExplorer_pb2

class TransExplorerStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    OpenConnection: grpc.UnaryUnaryMultiCallable[
        transExplorer_pb2.ConnectRequest,
        transExplorer_pb2.Connection]

    LoadModel: grpc.UnaryUnaryMultiCallable[
        transExplorer_pb2.LoadModelRequest,
        transExplorer_pb2.LoadModelResponse]
    """TODO rpc Terminate (TerminateRequest) returns (TerminationReply) {}"""


class TransExplorerServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def OpenConnection(self,
        request: transExplorer_pb2.ConnectRequest,
        context: grpc.ServicerContext,
    ) -> transExplorer_pb2.Connection: ...

    @abc.abstractmethod
    def LoadModel(self,
        request: transExplorer_pb2.LoadModelRequest,
        context: grpc.ServicerContext,
    ) -> transExplorer_pb2.LoadModelResponse:
        """TODO rpc Terminate (TerminateRequest) returns (TerminationReply) {}"""
        pass


def add_TransExplorerServicer_to_server(servicer: TransExplorerServicer, server: grpc.Server) -> None: ...
