"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import chai.transExplorer_pb2
import grpc

class TransExplorerStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    OpenConnection: grpc.UnaryUnaryMultiCallable[
        chai.transExplorer_pb2.ConnectRequest,
        chai.transExplorer_pb2.Connection]

    LoadModel: grpc.UnaryUnaryMultiCallable[
        chai.transExplorer_pb2.LoadModelRequest,
        chai.transExplorer_pb2.LoadModelResponse]
    """TODO rpc Terminate (TerminateRequest) returns (TerminationReply) {}"""


class TransExplorerServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def OpenConnection(self,
        request: chai.transExplorer_pb2.ConnectRequest,
        context: grpc.ServicerContext,
    ) -> chai.transExplorer_pb2.Connection: ...

    @abc.abstractmethod
    def LoadModel(self,
        request: chai.transExplorer_pb2.LoadModelRequest,
        context: grpc.ServicerContext,
    ) -> chai.transExplorer_pb2.LoadModelResponse:
        """TODO rpc Terminate (TerminateRequest) returns (TerminationReply) {}"""
        pass


def add_TransExplorerServicer_to_server(servicer: TransExplorerServicer, server: grpc.Server) -> None: ...
